### PR TITLE
done with the search feature --tested from my side  --application wor…

### PR DESCRIPTION
**Pull request by yashdreamsdevelopment**
ready to merge

### CODE REVIEW

**Comment by Ak-Krishna** [comment]
All done in student library project is ready to run

**Comment by Ak-Krishna** [comment]
Good morning ,As per your pull request I had merged your code but I would to tell you that or in my opinion ,if we will try to fetch student name  instead of book name ,cause of sometimes many student can issue same book and that time it’s hard to find one user . student name is unique and we can easily fetch the input. Sent from Mail for Windows From: yashdreamsdevelopmentSent: 25 February 2022 09:57To: Ak-Krishna/ProjectsCc: SubscribedSubject: [Ak-Krishna/Projects] done with the search feature --tested from my side --application wor… (PR #2) ready to mergeYou can view, comment on, or merge this pull request online at:  https://github.com/Ak-Krishna/Projects/pull/2Commit Summary6565c47 done with the search feature --tested from my side --application working fineFile Changes (2 files)M Student_Library/index.html (17) M Student_Library/script.js (20) Patch Links:https://github.com/Ak-Krishna/Projects/pull/2.patchhttps://github.com/Ak-Krishna/Projects/pull/2.diff—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by yashdreamsdevelopment** [comment]
I will see into it,
just find the class name i.e. given into the table row for the book name, replace that for the student name and all the application should run the same as before

**Comment by Ak-Krishna** [comment]
Ok, I will do that.

**Comment by yashdreamsdevelopment** [comment]
check the infyTQ results

**Pull request merged**
